W:\MessageBrokerSystem\.venv\Scripts\python.exe W:\WindowsLogScanner\main.py 
 * Serving Flask app 'main'
 * Debug mode: on
2025-05-05 18:00:32,085 - werkzeug - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.100.167:5000
2025-05-05 18:00:32,085 - werkzeug - INFO - Press CTRL+C to quit
2025-05-05 18:00:32,087 - werkzeug - INFO -  * Restarting with stat
2025-05-05 18:00:32,425 - werkzeug - WARNING -  * Debugger is active!
2025-05-05 18:00:32,427 - werkzeug - INFO -  * Debugger PIN: 801-986-691
2025-05-05 18:00:34,861 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:34] "GET / HTTP/1.1" 200 -
2025-05-05 18:00:35,343 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:35] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:00:35,346 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:35] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:00:38,207 - web - ERROR - Ошибка при подключении к RabbitMQ: 'charmap' codec can't decode byte 0x98 in position 609: character maps to <undefined>
2025-05-05 18:00:38,207 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:38] "POST /api/connect-rabbitmq HTTP/1.1" 200 -
2025-05-05 18:00:44,669 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:44] "GET /settings HTTP/1.1" 500 -
Traceback (most recent call last):
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\WindowsLogScanner\main.py", line 67, in settings
    config = yaml.safe_load(config_file) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 609: character maps to <undefined>
2025-05-05 18:00:44,723 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:44] "GET /settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2025-05-05 18:00:44,732 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:44] "GET /settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2025-05-05 18:00:44,785 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:44] "GET /settings?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2025-05-05 18:00:47,314 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:47] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:00:48,416 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:48] "GET /settings HTTP/1.1" 500 -
Traceback (most recent call last):
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\WindowsLogScanner\main.py", line 67, in settings
    config = yaml.safe_load(config_file) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 609: character maps to <undefined>
2025-05-05 18:00:48,426 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:48] "GET /settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
2025-05-05 18:00:48,431 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:48] "GET /settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
2025-05-05 18:00:53,911 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:53] "GET /logs HTTP/1.1" 200 -
2025-05-05 18:00:53,932 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:00:53] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:01:02,139 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:02] "GET / HTTP/1.1" 200 -
2025-05-05 18:01:02,155 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:02] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:01:02,164 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:02] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:01:08,237 - web - ERROR - Ошибка при подключении к RabbitMQ: 'charmap' codec can't decode byte 0x98 in position 609: character maps to <undefined>
2025-05-05 18:01:08,237 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:08] "POST /api/connect-rabbitmq HTTP/1.1" 200 -
2025-05-05 18:01:12,677 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:12] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:01:22,645 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:22] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:01:32,642 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:32] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:01:42,638 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:42] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:01:52,162 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:52] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:01:58,430 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:58] "GET /logs HTTP/1.1" 200 -
2025-05-05 18:01:58,459 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:01:58] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:02:08,461 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:08] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:02:11,551 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:11] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:12,528 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:12] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:13,774 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:13] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:14,231 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:14] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:14,422 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:14] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:14,895 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:14] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:15,311 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:15] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:15,664 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:15] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:16,006 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:16] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:16,470 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:16] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:17,080 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:17] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:17,598 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:17] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:18,079 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:18] "GET /api/agent-logs?max_entries=1000 HTTP/1.1" 200 -
2025-05-05 18:02:18,458 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:18] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:02:19,024 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:19] "GET /settings HTTP/1.1" 500 -
Traceback (most recent call last):
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\WindowsLogScanner\main.py", line 67, in settings
    config = yaml.safe_load(config_file) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 609: character maps to <undefined>
2025-05-05 18:02:19,036 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:19] "GET /settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
2025-05-05 18:02:19,040 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:02:19] "GET /settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
2025-05-05 18:03:09,708 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:03:09] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:03:11,307 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:03:11] "GET / HTTP/1.1" 200 -
2025-05-05 18:03:11,328 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:03:11] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:03:11,334 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:03:11] "GET /api/status HTTP/1.1" 200 -
2025-05-05 18:03:15,151 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:03:15] "GET /settings HTTP/1.1" 500 -
Traceback (most recent call last):
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\WindowsLogScanner\main.py", line 67, in settings
    config = yaml.safe_load(config_file) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "W:\MessageBrokerSystem\.venv\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 609: character maps to <undefined>
2025-05-05 18:03:15,158 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:03:15] "GET /settings?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
2025-05-05 18:03:15,159 - werkzeug - INFO - 192.168.100.167 - - [05/May/2025 18:03:15] "GET /settings?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
